default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  port: 5432
  username: saharak
  password:

development:
  <<: *default
  database: ruby_on_rails_dev

test:
  <<: *default
  database: ruby_on_rails_test

production:
  <<: *default
  database: ruby_on_rails
